### PR TITLE
Cache error, late initialization error

### PR DESCRIPTION
**Pull request by deakjahn**
The two items we discussed in https://github.com/espresso3389/flutter_pdf_render/issues/68.

Thinking about it, even if using the key works as you suggested, I'd still modify that cache allocation. A simple check and avoids a strange error that's not obvious at first sight.

### CODE REVIEW

**Comment by espresso3389** [comment]
Aside from the original issue, the PR upgrades `targetSdkVersion` to 31. I'm not sure whether it's OK for everyone or not; SDK 31 has many breaking changes and sometime it breaks things like BLE and splashscreen.

Do you think how important the SDK changes is?

**Review by espresso3389 — APPROVED** [review]
I'm not sure whether example should have targetSdkVersion 31 or not but the changes are reasonable.

**Comment by deakjahn** [comment]
Yep, I mentioned that in the comment. I don't think it's important to change the SDK but simply, it didn't compile here without the change. I don't know why...

**Comment by espresso3389** [comment]
OK, anyway, I merged the PR. I'll release a new version soon.

**Comment by deakjahn** [comment]
Thanks. I started to create my own layouts and I can see some zooming issues now but I don't yet know if it's my error. Basically, when I change PDF, I call `controller.goToPage(pageNumber: 1)` to make sure it doesn't get stuck on a non existing page (if the first PDF had three pages, we were on the third, but the new one only has two). Jumping to the page changes the zoom, sometimes just like I wanted it, sometimes smaller.

**Comment by espresso3389** [comment]
[1.0.20](https://pub.dev/packages/pdf_render/versions/1.0.20) is released!

**Comment by deakjahn** [comment]
Yep, I got the Kotlin errors back. I'll copy some of them to see what might be different at your end:

```
e: Incompatible classes were found in dependencies. Remove them from the classpath or use '-Xskip-metadata-version-check' to suppress errors
e: .gradle/caches/transforms-3/0d64d5ad66f017e06ac265767a913ba4/transformed/jetified-kotlin-stdlib-jdk7-1.6.10.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
e: .gradle/caches/transforms-3/291849b43d73afe58bebff41f4579b4b/transformed/jetified-kotlin-stdlib-common-1.6.10.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
e: .gradle/caches/transforms-3/812cefd60c93c07d26443ae2beafad7e/transformed/jetified-kotlin-stdlib-1.6.10.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
e: E:\Android\flutter\.pub-cache\hosted\pub.dartlang.org\pdf_render-1.0.20\android\src\main\kotlin\jp\espresso3389\pdf_render\PdfRenderPlugin.kt: (38, 10): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
The class is loaded from .gradle/caches/transforms-3/812cefd60c93c07d26443ae2beafad7e/transformed/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
```

This is why I needed to change Kotlin version. Maybe because my own app is in a different one?

**Comment by deakjahn** [comment]
Ooops. Some SO answers suggest that the answer might be as simple as you forgot to change jcenter() with mavenCentral() in the gradle file... :-)

**Comment by deakjahn** [comment]
Forget it. My bad, my Kotlin version in my own app was old. Sorry.

**Comment by deakjahn** [comment]
I have beautiful 2-up display now. :-)

**Comment by deakjahn** [comment]
Two page spreads. No gaps horizontally, gap vertically. Beautiful :-)

Screenshot_20220117_133620

**Comment by deakjahn** [comment]
Yes, it is. On Android. I can't get any display on iOS (Simulator). I've just updated to Monterey and Xcode 13 because of another package and compilation problems. Do you happen to have any feedback if this causes issues?

I get completely blank pages but correct layout and page decoration shadow boxes, so the PDF is read, just some display problem.

**Comment by espresso3389** [comment]
@deakjahn
> Attempted to composite external textures using the software back end.

pdf_render uses Flutter's Texture that is realized by Metal API on iOS.
And, based on [Apple's document](https://developer.apple.com/documentation/metal/developing_metal_apps_that_run_in_simulator), Xcode 11 adds iOS simulator Metal support.

So the cause is not Xcode 13. We should check other things.

Anyway, please open another issue to discuss such issues.

**Comment by espresso3389** [comment]
@deakjahn
According to [this](https://github.com/flutter/engine/pull/17881), iOS simulator uses Metal backend if >= iOS13, >= Catalina.

**Comment by deakjahn** [comment]
@espresso3389 Fair enough, but I won't. I realized the reason: I run my Xcode on a macOS in a VM. So, sadly, it won't work. Not worth to start an issue for it. :-)

**Pull request merged**
