### PR TITLE
Update build.gradle

### PR DESCRIPTION
**Pull request by petanon**

### CODE REVIEW

**Comment by esaiamuthan** [comment]
Hi @here kindly merge this PR please am getting some issues with my project

**Comment by esaiamuthan** [comment]
@animator @espresso3389 @deakjahn 
Any one of you kindly merge it please its very urgent for my project

**Comment by esaiamuthan** [comment]
Thanks for the reply

Hi @petanon  can you proceed to merge this PR please with the owner of this package, it will helpful for other peoples.

Or else kindly give us entire access let me take care of entire maintenance.

Thanks

**Review by espresso3389 — APPROVED** [review]

**Comment by esaiamuthan** [comment]
Hi @espresso3389  when you have time to check this package kindly update it for Android 34 and latest iOS targets 

Thanks in advance

**Pull request merged**
